- name: install rpmfusion repositories
  when: ansible_distribution == 'Fedora'
  dnf: name={{item}} state=latest
  sudo: yes
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

- name: install gstreamer plugins
  when: ansible_distribution == 'Fedora'
  dnf: name={{item}} state=latest
  sudo: yes
  with_items:
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-ugly