- name: setup dircolors
  template: src=dircolors dest={{ansible_user_dir}}/.dircolors

- name: set terminal font
  gsettings: schema="org.gnome.desktop.interface" key="monospace-font-name" value="Liberation Mono 10"

- name: set terminal keybindings
  gsettings: schema="org.gnome.Terminal.Legacy.Keybindings:/" key="{{ item.name }}" value="{{ item.as }}"
  with_items:
    - { name: switch-to-tab-3, as: 'disabled' }
    - { name: new-profile, as: 'disabled' }
    - { name: switch-to-tab-35, as: 'disabled' }
    - { name: switch-to-tab-6, as: 'disabled' }
    - { name: reset, as: 'disabled' }
    - { name: zoom-out, as: 'disabled' }
    - { name: switch-to-tab-33, as: 'disabled' }
    - { name: switch-to-tab-19, as: 'disabled' }
    - { name: switch-to-tab-4, as: 'disabled' }
    - { name: switch-to-tab-5, as: 'disabled' }
    - { name: switch-to-tab-7, as: 'disabled' }
    - { name: switch-to-tab-20, as: 'disabled' }
    - { name: switch-to-tab-21, as: 'disabled' }
    - { name: switch-to-tab-22, as: 'disabled' }
    - { name: move-tab-left, as: 'disabled' }
    - { name: find-clear, as: '<Control><Shift>J' }
    - { name: switch-to-tab-24, as: 'disabled' }
    - { name: reset-and-clear, as: 'disabled' }
    - { name: help, as: 'disabled' }
    - { name: switch-to-tab-25, as: 'disabled' }
    - { name: find, as: '<Control><Shift>F' }
    - { name: switch-to-tab-27, as: 'disabled' }
    - { name: switch-to-tab-28, as: 'disabled' }
    - { name: switch-to-tab-26, as: 'disabled' }
    - { name: switch-to-tab-23, as: 'disabled' }
    - { name: switch-to-tab-34, as: 'disabled' }
    - { name: prev-tab, as: 'disabled' }
    - { name: new-window, as: 'disabled' }
    - { name: switch-to-tab-9, as: 'disabled' }
    - { name: copy, as: '<Ctrl><Shift>c' }
    - { name: full-screen, as: 'F11' }
    - { name: save-contents, as: 'disabled' }
    - { name: zoom-normal, as: 'disabled' }
    - { name: zoom-in, as: 'disabled' }
    - { name: move-tab-right, as: 'disabled' }
    - { name: toggle-menubar, as: 'disabled' }
    - { name: close-window, as: 'disabled' }
    - { name: switch-to-tab-1, as: 'disabled' }
    - { name: switch-to-tab-10, as: 'disabled' }
    - { name: switch-to-tab-11, as: 'disabled' }
    - { name: new-tab, as: 'disabled' }
    - { name: switch-to-tab-13, as: 'disabled' }
    - { name: switch-to-tab-12, as: 'disabled' }
    - { name: paste, as: '<Ctrl><Shift>v' }
    - { name: switch-to-tab-17, as: 'disabled' }
    - { name: detach-tab, as: 'disabled' }
    - { name: close-tab, as: 'disabled' }
    - { name: find-next, as: '<Control><Shift>G' }
    - { name: switch-to-tab-15, as: 'disabled' }
    - { name: switch-to-tab-16, as: 'disabled' }
    - { name: switch-to-tab-32, as: 'disabled' }
    - { name: find-previous, as: '<Control><Shift>H' }
    - { name: next-tab, as: 'disabled' }
    - { name: switch-to-tab-2, as: 'disabled' }
    - { name: switch-to-tab-29, as: 'disabled' }
    - { name: switch-to-tab-18, as: 'disabled' }
    - { name: switch-to-tab-14, as: 'disabled' }
    - { name: switch-to-tab-30, as: 'disabled' }
    - { name: switch-to-tab-31, as: 'disabled' }
    - { name: switch-to-tab-8, as: 'disabled' }
