- name: install xchat
  package: name=xchat state=latest
  sudo: yes

- name: create config folder
  file:
    path={{ansible_user_dir}}/.config/xchat2
    state=directory
    recurse=yes

- name: copy config
  copy:
    src=xchat-servlist.conf
    dest={{ansible_user_dir}}/.config/xchat2/servlist_.conf